### ISSUE TITLE
feat: Authentication Activity

### ISSUE THREAD

**Issue by algonacci** [travens-id/bangkit-mobile-development#3]
- [x] Register with email
- [x] Login with email

**Comment by Widi-ps** [comment]
#13 udah aku pr yah, kalo ada yang kurang bilang aja mas @algonacci @setyofp

**Comment by Widi-ps** [comment]
#14 udah aku tambahin overlay sama betulin button nya mas @algonacci

**Comment by algonacci** [comment]
> #14 udah aku tambahin overlay sama betulin button nya mas @algonacci

Okee mas, lanjut yang profile yaa mas. Semangat" 🔥
